# Generated by Django 4.1.7 on 2023-03-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('killer', models.BooleanField(default=False)),
                ('num_turns', models.IntegerField(blank=True, null=True)),
                ('banished', models.BooleanField(default=False)),
                ('actions', models.JSONField(blank=True, null=True)),
                ('votes', models.JSONField(blank=True, null=True)),
                ('killed', models.BooleanField(default=False)),
                ('escaped', models.BooleanField(default=False)),
                ('num_killed', models.IntegerField(blank=True, null=True)),
                ('num_basished', models.IntegerField(blank=True, null=True)),
                ('num_escaped', models.IntegerField(blank=True, null=True)),
                ('witness_during_vote', models.JSONField(blank=True, null=True)),
                ('vote_rate_for_self', models.FloatField(blank=True, null=True)),
                ('vote_rate_for_killer', models.FloatField(blank=True, null=True)),
                ('witness_vote_rate_for_killer', models.FloatField(blank=True, null=True)),
                ('non_witness_vote_rate_for_killer', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicate_search_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('story', models.CharField(blank=True, max_length=65535, null=True)),
            ],
        ),
    ]
